{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "roundtable-ui.serviceAccountName" . }}
  labels:
    {{- include "roundtable-ui.labels" . | nindent 4 }}
{{- end }}
